### ISSUE TITLE
MAP: in Learning Theory Code

### ISSUE THREAD

**Issue by suzbert** [unpingco/Python-for-Probability-Statistics-and-Machine-Learning#2]
In: https://github.com/unpingco/Python-for-Probability-Statistics-and-Machine-Learning/blob/master/chapters/machine_learning/notebooks/learning_theory.ipynb the map

Code:
train['xb']= train.x.map('{0:010b}'.format)
train.y=train.xb.map(f_target)
train.head(5)
####yields output including:  x = 15, y = <map object at 0x00000246E4890198>, xb = 0000001111
...
train.y.values.reshape(10,-1).mean(axis=1)
####Errored out TypeError: unsupported operand type(s) for +: 'map' and 'map'

![2018-08-14 17_12_50 pfpsaml_learning_theory](https://user-images.githubusercontent.com/8960381/44118929-9d06d0d0-9fe5-11e8-8880-cecb524a7115.png)

My attempts to convert to list per stackoverflow have been unsuccessful, 
As (obviously) my attempts to replicate the table published in the github notebook  (see attached figure).

Ask: Is there a workaround you recommend I use? Note: I'm new at ML in python.
Suzanne

**Comment by unpingco** [comment]
Are you running this with a Python 3 kernel? It should say on the upper right of the Jupyter notebook.
